name: Build

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Run Build
        run: |
          npm ci
          npm test
          npm run build
