name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Run Build
        run: |
          npm ci
          npm test
          npm run build

      - name: Publish NPM Package
        id: package
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Distribution
        if: ${{ steps.package.outputs.new-release-published }}
        run: npm run dist
        env:
          NODE_PKG_VERSION: ${{ steps.package.outputs.release-version }}

      - name: FTP Assets to CDN
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: ./dist/
          server-dir: ./design-tokens/
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
